127.0.0.1: 
    - localhost
"::1":
    - localhost
    - ipv6-localhost
    - ipv6-loopback
"fe00::0":
    - ipv6-localnet
"ff00::0":
    - ipv6-mcastprefix
"ff02::1":
    - ipv6-allnodes
"ff02::2":
    - ipv6-allrouters
"ff02::3":
    - ipv6-allhosts
74.207.247.199:
    - makemeaworld.com
192.168.1.84:
    - james-pc

